services:
  backend:
    build: ./backend
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - REDIS_URL=${REDIS_URL}
      - CELERY_TASK_ALWAYS_EAGER=${CELERY_TASK_ALWAYS_EAGER}

  frontend:
    build: ./frontend
    ports:
      - "80:80" 
    depends_on:
      - backend

  worker:
    build: ./backend
    command: celery -A config worker --loglevel=info
    environment:
      - REDIS_URL=${REDIS_URL}
      - CELERY_TASK_ALWAYS_EAGER=${CELERY_TASK_ALWAYS_EAGER}
    depends_on:
      - backend
